### ISSUE TITLE
Issue with walking animation and jumps

### ISSUE THREAD

**Issue by JeidoUran** [SapphireMordred/Sapphire#332] opened 2018-07-03 21:47 UTC
There are currently issues with the walking animation and the jumps.

- [ ] If a player sets themselves to be walking, they will appear using the running animation while moving at a reduced speed for other players.

- [ ] If a player jumps, they appear to be jumping twice in a row for other players.

**Comment by SapphireMordred** [comment] 2018-07-17 14:20
duplicate of #32

**Closed by SapphireMordred** 2018-07-17 14:20 UTC
